### ISSUE TITLE
Network Watch tool causes Knots to crash (?)

### ISSUE THREAD

**Issue by grubles** [bitcoinknots/bitcoin#4]
`user@stuffVM:~$ bitcoin-qt: qt/netwatch.cpp:547: void NetWatchLogModel::log_append(const LogEntry&, size_t&): Assertion ``!logpos' failed.`

`[2]+  Aborted                 bitcoin-0.14.0/bin/bitcoin-qt`

Qubes OS 3.2
Knots 0.14.0 running in a Fedora 24 AppVM

**Comment by grubles** [comment]
Just tested this on Debian Jessie 8.7 and it also crashes in the same way.

**Comment by AndyLavr** [comment]
Patch fixed this problem:


```bash

diff -ENwbur ./bk-src.orig/src/qt/netwatch.cpp ./bk-src/src/qt/netwatch.cpp
--- ./bk-src.orig/src/qt/netwatch.cpp	2017-08-18 09:57:03.000000000 +0300
+++ ./bk-src/src/qt/netwatch.cpp	2017-08-18 13:54:28.000000000 +0300
@@ -543,9 +543,14 @@
         getLogEntryRow(rows_used) = le;
         --logskip;
     } else {
+
         // Haven't filled up yet, so just push_back
-        assert(!logpos);
+    if (!logpos) {
+        qWarning("Haven't filled up yet, so just push_back...");
+    }
+
         log.push_back(le);
+
     }
     ++rows_used;
     if (rows_used > max_nonweak_txouts) {
diff -ENwbur ./bk-src.orig/src/qt/netwatch.h ./bk-src/src/qt/netwatch.h
--- ./bk-src.orig/src/qt/netwatch.h	2017-08-18 09:57:03.000000000 +0300
+++ ./bk-src/src/qt/netwatch.h	2017-08-18 12:43:18.000000000 +0300
@@ -12,6 +12,9 @@
 #include <QAbstractTableModel>
 #include <QWidget>
 
+#define NDEBUG
+#define QT_NO_DEBUG
+
 QT_BEGIN_NAMESPACE
 class QLineEdit;
 class QTableView;



```

Best regards, Andy Lavr.

**Comment by AndyLavr** [comment]
To All:

Use my fix and work quietly without dropping your wallet.

**Comment by luke-jr** [comment]
Users should be advised that @AndyLavr's patch is NOT a fix, and causes incorrect behaviour rather than aborting.

(Also note that you can avoid the issue entirely by simply never opening the Network Watch tool)

**Comment by luke-jr** [comment]
(Also note that you can avoid the issue entirely by simply never opening the Network Watch tool)

**Comment by AndyLavr** [comment]
This behavior can still be achieved without installing or launching a wallet. :)

The developer is sure that annoying users with new non-working features is very good. :)))))

**Comment by AndyLavr** [comment]
Also note that you can avoid the issue entirely by simply never use this project... ^))))))))))))))))))))))))))

**Comment by AndyLavr** [comment]
To all: 

use - https://github.com/bitcoin/bitcoin

There are no stupid ...

**Comment by luke-jr** [comment]
(blocking @AndyLavr for trolling)

**Comment by luke-jr** [comment]
Finally tracked this down! It occurs when the circular log buffer hasn't quite filled yet, but old entries need to be pruned anyway due to the new transaction having more outputs than remaining slots.

For example, only 1 more entry to reach 100% full, but the transaction being added has 2 outputs. In this case, it deletes the oldest entry, replaces it with the first output, and then gets confused when it tries to add the 2nd output, since there's no deleted entries to replace anymore and the "start" entry isn't the start of the list.

The solution is to check if we're adding an entirely new entry row before doing any replacement of deleted entries.

Note: This isn't high enough priority for a new release. If you want to patch your own build, see https://github.com/luke-jr/bitcoin/commit/3aa63af026333e247faceb24c675d91a3f06f375 ([raw patch file](https://github.com/luke-jr/bitcoin/commit/3aa63af026333e247faceb24c675d91a3f06f375.patch))
